import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
const version = pkg.version;

// ── Shared fields ──
const shared = {
  manifest_version: 3,
  name: "Civit model downloader",
  description: "Extension for download models with full metadata from Civitai",
  version,
  icons: {
    "16": "icons/icon16.png",
    "32": "icons/icon32.png",
    "48": "icons/icon48.png",
    "64": "icons/icon64.png",
    "128": "icons/icon128.png",
  },
  options_ui: {
    page: "options.html",
    open_in_tab: true,
  },
  content_scripts: [
    {
      matches: ["*://civitai.com/*", "*://civitai.red/*"],
      js: ["build/content.js"],
      css: ["build/content.css"],
    },
  ],
  permissions: ["storage", "downloads"],
};

// ── Chrome manifest ──
const chromeManifest = {
  ...shared,
  action: {
    browser_style: true,
    default_icon: "icons/icon48.png",
    default_popup: "popup.html",
    default_title: "Civit model downloader",
  },
  background: {
    service_worker: "build/service_worker.js",
    type: "module",
  },
};

// ── Firefox manifest ──
const firefoxManifest = {
  ...shared,
  browser_specific_settings: {
    gecko: {
      id: "civitdownloader@aksionau.com",
    },
  },
  action: {
    default_icon: "icons/icon48.png",
    default_popup: "popup.html",
    default_title: "Civit model downloader",
  },
  background: {
    scripts: ["build/background.js"],
    type: "module",
  },
};

// ── Write manifests ──
const chromeDir = path.join(root, 'static');
const firefoxDir = path.join(root, 'static_ff');

fs.mkdirSync(chromeDir, { recursive: true });
fs.mkdirSync(firefoxDir, { recursive: true });

fs.writeFileSync(
  path.join(chromeDir, 'manifest.json'),
  JSON.stringify(chromeManifest, null, 2) + '\n',
);
fs.writeFileSync(
  path.join(firefoxDir, 'manifest.json'),
  JSON.stringify(firefoxManifest, null, 2) + '\n',
);

// ── Write version.ts ──
const versionDir = path.join(root, 'src', 'lib');
fs.mkdirSync(versionDir, { recursive: true });
fs.writeFileSync(
  path.join(versionDir, 'version.ts'),
  `// Auto-generated by scripts/manifest.mjs — do not edit manually\nexport const currentVersion = "${version}";\n`,
);

console.log(`Generated manifests and version.ts for v${version}`);
